### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by joshp23** [joshp23/YOURLS-Snapshot#1]
This is a list of planned feature enhancements and improvements that may or may not ever get done

- [ ] add an option to easily use a custom template to display the preview page
- [ ] add share functions to the preview page (eq [IQRCodes](https://github.com/joshp23/YOURLS-IQRCodes))
- [x] add more details about the destination URL to the preview page (e.g. a safety check via ~~http:BL or~~ Phishtank)
- [x] option to delete cache on plugin disable
- [x] split U-SRV off into its own plugin
- [ ] Restructure setup so that the cache is not automatically created, but permissions are checked in advance, etc...

**Comment by joshp23** [comment]
Integration is set up with the addition of srv.php
